name: Tự động deploy lên Server Ubuntu khi có Code mới

on:
  push:
    branches: ["main"] # Kích hoạt khi có người push code lên nhánh main

jobs:
  # ci-check:
  #   name: Kiểm tra mã nguồn (CI)
  #   runs-on: ubuntu-latest # Chạy trên server đám mây của GitHub

  #   steps:
  #     - name: Lấy mã nguồn mới nhất
  #       uses: actions/checkout@v4 # Cập nhật lên v4 cho đồng bộ

  #     - name: Giả lập môi trường Node.js
  #       uses: actions/setup-node@v4 # Cập nhật lên v4

  #       with:
  #         node-version: "20"

  #     - name: Cài đặt thư viện Frontend
  #       run: |
  #         cd frontend
  #         npm install

  #     - name: Chạy thử Build Frontend (Dry Build)
  #       run: |
  #         cd frontend
  #         npm run build
  #         echo "Code Frontend hoàn toàn sạch sẽ, không có lỗi cú pháp!"

  deploy:
    runs-on: self-hosted # Ép kịch bản này chạy trên con Ubuntu (Runner) của bạn

    steps:
      # Bước 1: Kéo code mới nhất từ GitHub về thư mục làm việc của Runner trên Ubuntu
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      # Bước 2: Ra lệnh cho Docker dập container cũ, build và bật container mới lên
      - name: Khởi chạy Docker Compose

        run: |
          docker compose down --remove-orphans || true
          docker compose up -d --build
